/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package wofpractice;

import static wofpractice.WOFPractice.choices;
import static wofpractice.WOFPractice.order;
import static wofpractice.WOFPractice.solution;
import static wofpractice.WOFPractice.stepOne;
import static wofpractice.WOFPractice.wordList;
import java.*;
import java.awt.Color;

/**
 *
 * @author Matthew
 */
public class ModuleGUI extends javax.swing.JFrame {

    /**
     * Creates new form ModuleGUI
     */
    public ModuleGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        topWord = new javax.swing.JLabel();
        position1 = new javax.swing.JButton();
        position2 = new javax.swing.JButton();
        position3 = new javax.swing.JButton();
        position4 = new javax.swing.JButton();
        position5 = new javax.swing.JButton();
        position6 = new javax.swing.JButton();
        result = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jRadioButton1 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Who's on First Practice");

        topWord.setBackground(new java.awt.Color(255, 255, 255));
        topWord.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        topWord.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        topWord.setText("Top Word");
        topWord.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 10));
        topWord.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        topWord.setOpaque(true);

        position1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        position1.setText("Word 1");
        position1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        position1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                position1ActionPerformed(evt);
            }
        });

        position2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        position2.setText("Word 2");
        position2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        position2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                position2ActionPerformed(evt);
            }
        });

        position3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        position3.setText("Word 3");
        position3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        position3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                position3ActionPerformed(evt);
            }
        });

        position4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        position4.setText("Word 4");
        position4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        position4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                position4ActionPerformed(evt);
            }
        });

        position5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        position5.setText("Word 5");
        position5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        position5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                position5ActionPerformed(evt);
            }
        });

        position6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        position6.setText("Word 6");
        position6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        position6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                position6ActionPerformed(evt);
            }
        });

        result.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        result.setText("Press any button to begin.");
        result.setToolTipText("");
        result.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(result, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(position1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(position2, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(position5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                                .addComponent(position3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(position4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(position6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addComponent(topWord, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButton1))
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(topWord, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(position2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(position1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(position4, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(position3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(position6, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(position5, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jRadioButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(result, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public boolean started = false;
    
    private void position1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_position1ActionPerformed
        // TODO add your handling code here:
        if (started==false){
            newSet();
            started = true;
        }
        else{
        String tx = position1.getText();
        if(tx.equals(WOFPractice.solution)){
            //Correct
            result.setForeground(new Color(0x00a000));
            result.setText("Correct!");
            newSet();
        }
        else{
            result.setForeground(Color.RED);
            result.setText("No, the correct answer was "+solution+".");
            newSet();
        }
        }
    }//GEN-LAST:event_position1ActionPerformed

    private void position2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_position2ActionPerformed
        // TODO add your handling code here:
        if (started==false){
            newSet();
            started = true;
        }
        else{
        String tx = position2.getText();
        if(tx.equals(WOFPractice.solution)){
            //Correct
            result.setForeground(new Color(0x00a000));
            result.setText("Correct!");
            newSet();
        }
        else{
            result.setForeground(Color.RED);
            result.setText("No, the correct answer was "+solution+".");
            newSet();
        }
        }
    }//GEN-LAST:event_position2ActionPerformed

    private void position3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_position3ActionPerformed
        // TODO add your handling code here:
        if (started==false){
            newSet();
            started = true;
        }
        else{
        String tx = position3.getText();
        if(tx.equals(WOFPractice.solution)){
            //Correct
            result.setForeground(new Color(0x00a000));
            result.setText("Correct!");
            newSet();
        }
        else{
            result.setForeground(Color.RED);
            result.setText("No, the correct answer was "+solution+".");
            newSet();
        }
        }
    }//GEN-LAST:event_position3ActionPerformed

    private void position4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_position4ActionPerformed
        // TODO add your handling code here:
        if (started==false){
            newSet();
            started = true;
        }
        else{
        String tx = position4.getText();
        if(tx.equals(WOFPractice.solution)){
            //Correct
            result.setForeground(new Color(0x00a000));
            result.setText("Correct!");
            newSet();
        }
        else{
            result.setForeground(Color.RED);
            result.setText("No, the correct answer was "+solution+".");
            newSet();
        }
        }
    }//GEN-LAST:event_position4ActionPerformed

    private void position5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_position5ActionPerformed
        // TODO add your handling code here:
        if (started==false){
            newSet();
            started = true;
        }
        else{
        String tx = position5.getText();
        if(tx.equals(WOFPractice.solution)){
            //Correct
            result.setForeground(new Color(0x00a000));
            result.setText("Correct!");
            newSet();
        }
        else{
            result.setForeground(Color.RED);
            result.setText("No, the correct answer was "+solution+".");
            newSet();
        }
        }
    }//GEN-LAST:event_position5ActionPerformed

    private void position6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_position6ActionPerformed
        // TODO add your handling code here:
        if (started==false){
            newSet();
            started = true;
        }
        else{
        String tx = position6.getText();
        if(tx.equals(WOFPractice.solution)){
            //Correct
            result.setForeground(new Color(0x00a000));
            result.setText("Correct!");
            newSet();
        }
        else{
            result.setForeground(Color.RED);
            result.setText("No, the correct answer was "+solution+".");
            newSet();
        }
        }
    }//GEN-LAST:event_position6ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModuleGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModuleGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModuleGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModuleGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModuleGUI().setVisible(true);
                //buttonSet("str");
            }
        });
        //buttonSet();
    }
    
    public void newSet(){
        wordList = Module.whichWord(0);
        choices = Module.answers(wordList);
        solution = Module.findAnswer(choices, wordList);
        stepOne = Module.stepOne(wordList[14]);
        order = Module.positionFive((String)stepOne[0], (int)stepOne[1], choices);
        position1.setText((String)WOFPractice.order[0]);
        position2.setText((String)WOFPractice.order[1]);
        position3.setText((String)WOFPractice.order[2]);
        position4.setText((String)WOFPractice.order[3]);
        position5.setText((String)WOFPractice.order[4]);
        position6.setText((String)WOFPractice.order[5]);
        topWord.setText((String)stepOne[0]);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JButton position1;
    private javax.swing.JButton position2;
    private javax.swing.JButton position3;
    private javax.swing.JButton position4;
    private javax.swing.JButton position5;
    private javax.swing.JButton position6;
    private javax.swing.JLabel result;
    private javax.swing.JLabel topWord;
    // End of variables declaration//GEN-END:variables
}
